### PR TITLE
Pin jsonschema

### PR DESCRIPTION
**Pull request by trungleduc**

### CODE REVIEW

**Comment by martinRenou** [comment]
Is it an issue with a newest jsonschema version?

**Review by martinRenou — APPROVED** [review]
Thanks!

**Comment by trungleduc** [comment]
> Is it an issue with a newest jsonschema version?

yes, it removes the `vocabularies.json` file

**Comment by trungleduc** [comment]
it works now!

**Comment by martinRenou** [comment]
Thanks!

**Pull request merged**
